### ISSUE TITLE
Remove random characters from code

### ISSUE THREAD

**Issue by snhs-r3c0n** [SullivanNorthHS/014-a-cli-cheatsheet-kyn-matt#9]
https://github.com/SullivanNorthHS/014-a-cli-cheatsheet-kyn-matt/blob/937620d68ef2efe755d9f9a95ccf25f6f71240d1/index.html#L85-L104

This seems to be a merging error, it would be best to remove this.

**Comment by Kenderlyn** [comment]
Thank you for you comment, ill fix it
